### ISSUE TITLE
pre-commit can't find `node` after installing with Poetry on NixOS

### ISSUE THREAD

**Issue by l0b0** [pre-commit/mirrors-prettier#10]
[pre-commit.log](https://github.com/pre-commit/mirrors-prettier/files/6965557/pre-commit.log)
I'm not sure whether this is a NixOS, Poetry, Node, pre-commit or PEBCAK issue, but here's how to reproduce:

```shell
git clone --recurse-submodules https://gitlab.com/victor-engmark/vcard.git
cd vcard
poetry install
poetry run pre-commit run --all-files prettier
```

The output:

```text
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: FileNotFoundError: [Errno 2] No such file or directory: '/home/victor/.cache/pre-commit/repoy_nkxk3a/node_env-default/bin/node'
Check the log at /home/victor/.cache/pre-commit/pre-commit.log
```

I've tried removing `/home/victor/.cache/pre-commit` completely, but that didn't help.

**Comment by asottile** [comment]
I've seen this before and that time [it was nixos](https://github.com/pre-commit/pre-commit/pull/1938#issuecomment-858802078) (missing libstdc++ or something?) -- you can reproduce by running the following:

```
nodeenv nenv --prebuilt
. nenv/bin/activate
node --version
```

you can _probably_ work around it by having an installation of `node` outside of pre-commit (such that it will default to `language_version: system`)
