### ISSUE TITLE
Entry point command line arguments are forced

### ISSUE THREAD

**Issue by aentwist** [pre-commit/mirrors-prettier#13]
I want to automatically format files on commit using this command, which should be successful.
```shell
prettier --write --ignore-unknown
```

Exit codes do not seem to be well-documented, but after formatting is done I can confirm that this has an exit code of 0.

I see that [this mirror's entry point](https://github.com/pre-commit/mirrors-prettier/blob/master/.pre-commit-hooks.yaml#L3) is:
```shell
prettier --write --list-different --ignore-unknown
```

This is unusable because `--list-different` has an exit code of 1 if any differences are found, i.e. any formatting is done [[1](https://prettier.io/docs/en/cli.html#exit-codes)].

Arguments specified in `entry` cannot be overridden [[2](https://pre-commit.com/#hooks-entry)].
entry | the entry point - the executable to run.  entry can also contain arguments that will not be overridden such as entry: autopep8 -i.
-- | --

I propose that going forward (next tag), `entry` is changed to `prettier`. This way consumers can use Prettier as they wish by specifying [`args`](https://pre-commit.com/#hooks-args).

[ESLint](https://github.com/pre-commit/mirrors-eslint) follows this example. While they could specify `--fix` in their entry point, they do not - it is just `eslint` [[3](https://github.com/pre-commit/mirrors-eslint/blob/master/.pre-commit-hooks.yaml#L3)].

Since pre-commit requires the specification of a tag or commit as the hook source, this would not break anything, although the change should be noted in the README.

If this is not possible I will fork this and make the change, as none of the [existing forks](https://github.com/pre-commit/mirrors-prettier/network/members) have it. In this case since this behavior is unexpected, it should be noted in the README.

**Comment by asottile** [comment]
> This is unusable because --list-different has an exit code of 1 if any differences are found, i.e. any formatting is done [1].

independent of that, if changes are made to files then pre-commit fails the patch

from [the docs](https://pre-commit.com/#creating-new-hooks)

> The hook must exit nonzero on failure or modify files.

___

you can override `entry` if you need to -- usually you don't need to.  the text you linked to is specifically talking about `args`

the only option a consuming hook can't "override" is `id` -- and there's `alias` for that

**Comment by aentwist** [comment]
Don't know how I missed this stuff. Thanks!!!

We decided to override `entry`:
```yaml
entry: prettier --list-different --ignore-unknown
```
