### ISSUE TITLE
pre-commit hook is neglecting my changes

### ISSUE THREAD

**Issue by plazmakeks** [pre-commit/mirrors-prettier#16]
Hi,

i"m using the following configuration for prettier in my pre-commit hooks:

`   - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        entry: prettier --write "{modules,attribution_results_ui}/**/*.{js,css}"
        types:
          - "javascript"
          - "css"
`
as i only want to format js and css in specific folders. when changing an html file it's ignored as expected. however when changing an js in one of the two folders it's not formatted as it would be required (added some newlines). any idea how to solve that?

**Comment by asottile** [comment]
looks like your formatting is off -- watch this: [intro to markdown](https://youtu.be/1UodxuXj5Ao)

also [read this to answer your question](https://pre-commit.com/#filtering-files-with-types)
