### ISSUE TITLE
Error when Installing environment for pre-commit/mirrors-prettier

### ISSUE THREAD

**Issue by jgstew** [pre-commit/mirrors-prettier#25]
I get the following error when installing environment for prettier:  (inside of visual studio code / powershell terminal on Win10)

```
[INFO] Installing environment for https://github.com/pre-commit/mirrors-prettier.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('C:\\Users\\james\\.cache\\pre-commit\\repolhcz07g7\\node_env-default\\Scripts\\npm.CMD', 'install', '--dev', '--prod', '--ignore-prepublish', '--no-progress', '--no-save')
return code: 1
expected return code: 0
stdout: (none)
stderr:
    npm WARN config dev Please use --include=dev instead.
    npm WARN config production Use `--omit=dev` instead.
    npm ERR! Unexpected token '.'

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\james\AppData\Local\npm-cache\_logs\2022-07-31T15_17_09_027Z-debug-0.log

Check the log at C:\Users\james\.cache\pre-commit\pre-commit.log
```

Relevant error in the npm log:

```
31 timing npm:load:logFile Completed in 4ms
32 timing npm:load:timers Completed in 0ms
33 timing npm:load:configScope Completed in 0ms
34 timing npm:load Completed in 19ms
35 verbose stack C:\Users\james\.cache\pre-commit\repolhcz07g7\node_env-default\Scripts\node_modules\npm\node_modules\libnpmfund:1
35 verbose stack ../workspaces/libnpmfund
35 verbose stack ^
35 verbose stack
35 verbose stack SyntaxError: Unexpected token '.'
35 verbose stack     at Object.compileFunction (node:vm:360:18)
35 verbose stack     at wrapSafe (node:internal/modules/cjs/loader:1049:15)
35 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1084:27)
35 verbose stack     at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
35 verbose stack     at Module.load (node:internal/modules/cjs/loader:998:32)
35 verbose stack     at Module._load (node:internal/modules/cjs/loader:839:12)
35 verbose stack     at Module.require (node:internal/modules/cjs/loader:1022:19)
35 verbose stack     at require (node:internal/modules/cjs/helpers:102:18)
35 verbose stack     at Object.<anonymous> (C:\Users\james\.cache\pre-commit\repolhcz07g7\node_env-default\Scripts\node_modules\npm\lib\utils\reify-output.js:16:38)
35 verbose stack     at Module._compile (node:internal/modules/cjs/loader:1120:14)
36 verbose cwd C:\Users\james\.cache\pre-commit\repolhcz07g7
37 verbose Windows_NT 10.0.19043
38 verbose node v18.7.0
39 verbose npm  v8.15.1
40 error Unexpected token '.'
41 verbose exit 1
42 timing npm Completed in 95ms
43 verbose code 1
```

My python / pip / pre-commit info:

```
python --version 
Python 3.10.5

pip --version
pip 22.2.1 from C:\Python310\lib\site-packages\pip (python 3.10)

pre-commit --version
pre-commit 2.20.0

nodeenv --version
1.3.3
```

**Comment by jgstew** [comment]
I just tried running it in CMD instead of PowerShell, same problem.

**Comment by asottile** [comment]
that looks like a symlink but written out as a file on disk -- appears to be a problem with `npm` itself and not anything we control -- please report your bug to upstream

**Comment by jgstew** [comment]
Install libnpmfund outside of this pre-commit worked just fine:

```
npm install libnpmfund

added 154 packages, and audited 155 packages in 1s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by asottile** [comment]
yeah it has nothing to do with installing libnpmfund -- there's a broken file in the node zip

**Comment by jgstew** [comment]
Is there a way to constrain it to a different node version that doesn't have this issue? Seems to be the line `../workspaces/libnpmfund` that is the issue.

**Comment by asottile** [comment]
I'm not going to tell you because you can just read the docs -- please understand that my free time is limited and I don't have the time to provide free support

**Comment by jgstew** [comment]
This seems like part of the issue: https://github.com/coreybutler/nvm-windows/issues/814

Running `pre-commit` in an admin prompt didn't fix the broken symlink issue, and gave the same issue.

Which docs?

**Comment by jgstew** [comment]
I can't quite tell a way to tell the prettier pre-commit hook to use a different node or npm version. It doesn't use my system Node version, instead using nodeenv to install one, but it always uses latest, which is broken it seems. I am not sure I can configure nodeenv because of the way it gets run within a virtualenv.

**Comment by jgstew** [comment]
prettier runs fine on the command line with node 16 LTS, but because I'm doing xml plugin, I had to add the following to my `.prettierrc.yaml` file:

`plugins: ["@prettier/plugin-xml"]`

Then run with the command:

`prettier --config .prettierrc.yaml -c **.xml`

But as far as I can tell, there is no easy way to get prettier to work through pre-commit on windows.

**Comment by jgstew** [comment]
Interesting, even though my nodeenv was updated, when I ran `nodeenv --version` it gave me an old version number.

Had to run:

```
pip uninstall nodeenv
pip install nodeenv
```

To fix that, but still didn't fix the issue. Annoying.

I did try a github action to test this pre-commit hook using try-repo, which fails for me locally, but worked on the github windows runner. I thought maybe it was because that defaults to a different shell, but that didn't seem to be it either.

Probably something weird with my environment, but I reinstalled python and it didn't fix it. So weird that this used to work just fine and then broke when updating some packages.

Here is the `test.yml` github action for testing the install of the env using try-repo:

```
---
name: test
on:
  push:
    branches: [main]

jobs:
  Test:
    strategy:
      matrix:
        # https://ncorti.com/blog/howto-github-actions-build-matrix
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-ver: ["3.8", "3"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-ver }}
      - name: install pre-commit
        run: pip install pre-commit
      - name: run pre-commit try-repo
        run: pre-commit try-repo .
```

Example run here: https://github.com/jgstew/mirrors-prettier/actions/runs/2770245273
