### ISSUE TITLE
this repo need SSL certificate from pre-commit!

### ISSUE THREAD

**Issue by ammar-khan-cultureamp** [pre-commit/mirrors-prettier#28]
I want to use this tool but it requires ssl from python virtual env 
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

All other pre-commit hooks are working fine

**Comment by asottile** [comment]
there's nothing special about this repo also you should paste your full output including the command you ran otherwise it's impossible to help you
