### ISSUE TITLE
Ignored unknown option - importOrder*

### ISSUE THREAD

**Issue by Borda** [pre-commit/mirrors-prettier#32]
Hello, not sure what is going wrong but for the local setting and calling `prettier` from the command line all seem to be working fine but when using a pre-commit hook, I see that these are not supported, it is some version issue?

```
[warn] Ignored unknown option { importOrderSeparation: true }.
[warn] Ignored unknown option { importOrderSortSpecifiers: true }.
[warn] Ignored unknown option { importOrder: ["^react$", "<THIRD_PARTY_MODULES>", "^(components|hooks|resources|types|utils)", "^tests", "^[./]"] }.
```

**Comment by asottile** [comment]
impossible to know, you haven't shared any information

**Comment by Borda** [comment]
> impossible to know, you haven't shared any information

hmm seems it is my local issue as can't reproduce in [CI](https://github.com/Lightning-AI/lightning-ui/actions/runs/3795206931/jobs/6454093175), apology :confused:

**Comment by almahdi404** [comment]
add this `"plugins": ["@trivago/prettier-plugin-sort-imports"]` to your **.prettierrc.json** file
