### ISSUE TITLE
Please provide working pre-commit syntax

### ISSUE THREAD

**Issue by edmundsj** [pre-commit/mirrors-prettier#35]
I have been unable to get this working with `pre-commit`. The following is the relevant section of my config file:

```
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: 2.8.3
    hooks:
    -   id: prettier
```

When I run pre-commit, I get the following error:

```
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'checkout', '2.8.3')
return code: 1
stdout: (none)
stderr:
    error: pathspec '2.8.3' did not match any file(s) known to git
    
Check the log at /home/jordan/.cache/pre-commit/pre-commit.log
```

2.8.3 is definitely the most recent version of prettier - not sure what's going on here. `pre-commit` works just fine with black and the sample config used. Can you provide known-good syntax instead of leaving the rev as `''`? This is confusing. I've tried using a SHA, tried putting the version in single quotes, double quotes, etc. Not sure how to fix this.

**Comment by asottile** [comment]
please search the issue tracker -- there are several duplicates
