### ISSUE TITLE
Missing 2.8.x prettier tags

### ISSUE THREAD

**Issue by JackHowa** [pre-commit/mirrors-prettier#38]
It seems like there's been some recent activity here on the missing tags. And I noticed in our update to prettier that it was also missing tags. 

It looks like prettier has updated tags for 2.8.3, for example, but they're not available here. https://github.com/prettier/prettier/tags https://github.com/prettier/prettier/releases/tag/2.8.3

The latest 2.x release here is on https://github.com/pre-commit/mirrors-prettier/releases/tag/v2.7.1

Let me know if I can help! 

Relates to https://github.com/pre-commit/mirrors-prettier/issues/37 @asottile @cj81499

**Comment by asottile** [comment]
search the issue tracker next time
