### ISSUE TITLE
--ignore-unknown used in tags older than 2.1.0

### ISSUE THREAD

**Issue by Yajo** [pre-commit/mirrors-prettier#6]
When using this hook for prettier versions older than 2.1.0, it still passes the `--ignore-unknown` CLI flag, which was only added on that version.

You can check it out in this 2.0.5 code (which was latest prettier release before that flag existed): https://github.com/pre-commit/mirrors-prettier/blob/408c101af984fcee7d4b238b52a73cd1d132f134/.pre-commit-hooks.yaml#L3

Check out this bash session:

```sh
root@31b78053d686:/# npm install -g prettier@2.0.5

changed 1 package, and audited 2 packages in 1s

found 0 vulnerabilities
root@31b78053d686:/# prettier --version
2.0.5
root@31b78053d686:/# prettier --help | grep unknown

#########

root@31b78053d686:/# npm install -g prettier@2.1.0

changed 1 package, and audited 2 packages in 740ms

found 0 vulnerabilities
root@31b78053d686:/# prettier --version
2.1.0
root@31b78053d686:/# prettier --help | grep unknown
  -u, --ignore-unknown     Ignore unknown files.
```

So, when you have a configuration like this one:

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v1.19.1
    hooks:
      - id: prettier
      - id: prettier
        name: prettier xml plugin
        additional_dependencies:
          - "prettier@1.19.1"
          - "@prettier/plugin-xml@0.7.2"
        files: \.xml$
```

You'll see random warnings if you run the hook in verbose mode (random because it will depend on how much parallelization is configured for pre-commit, because it will print one warn per execution, forcing it to ignore the 1st file in the list):

```
prettier xml plugin......................................................Passed
- hook id: prettier
- duration: 0.49s

[warn] Ignored unknown option --ignore-unknown=mail_activity_board/views/mail_activity_view.xml.
[warn] Ignored unknown option --ignore-unknown=mail_outbound_static/views/ir_mail_server_view.xml.
[warn] Ignored unknown option --ignore-unknown=mail_tracking_mailgun/views/res_partner.xml.
[warn] Ignored unknown option --ignore-unknown=mail_drop_target/views/templates.xml.
[warn] Ignored unknown option --ignore-unknown=mail_tracking/views/res_partner_view.xml.
[warn] Ignored unknown option --ignore-unknown=mass_mailing_event_registration_exclude/data/event_state_data.xml.
[warn] Ignored unknown option --ignore-unknown=mail_tracking/data/tracking_data.xml.
[warn] Ignored unknown option --ignore-unknown=mass_mailing_partner/views/mailing_view.xml.
[warn] Ignored unknown option --ignore-unknown=mail_full_expand/views/mail_full_expand.xml.
[warn] Ignored unknown option --ignore-unknown=mail_activity_done/views/templates.xml.
[warn] Ignored unknown option --ignore-unknown=mail_tracking/static/src/xml/failed_message/thread.xml.
```

So, the --ignore-unknown flag should be removed for old versions.

The only workaround so far is to override the `entry` when using them. Otherwise the hook is not reliable.

**Comment by asottile** [comment]
indeed, I guess not supporting <2.1 is the easiest -- I'll delete the old tags

**Comment by asottile** [comment]
oh actually it's just a warning not a failure so you should just ignore that

**Comment by Yajo** [comment]
Yes, but it makes prettier ignore those files, which shouldn't happen.

**Comment by asottile** [comment]
either way, there isn't really much that can be done so: https://github.com/pre-commit/mirrors-prettier/commit/d821bc8397f3700d8a844325dc27bdca40746494
